### ISSUE TITLE
-g arguments for install

### ISSUE THREAD

**Issue by jmcouffin** [ENG-Mazri/cli-ifcjs#2]
Hi, nice stuff, 
one note, for the install, in my setup, the npm package install was missing the -g argument to work

`npm i -g cli-ifcjs`

**Comment by ENG-Mazri** [comment]
Hello Jean!
hmm, It's working for me 🤔
![Снимок экрана (76)_LI](https://user-images.githubusercontent.com/84850871/174783459-9a4329f5-4832-4e0b-9718-cc547aa3b4f2.jpg)

**Comment by ENG-Mazri** [comment]
Or did you mean that it's working only when adding -g?
if so, that's true, thank you! I've modified that in the documentation

`npm i -g cli-ifcjs`

or 

`npx cli-ifcjs`

**Comment by jmcouffin** [comment]
Yes, exactly.
